#!/usr/bin/env python3
"""
events_build.py — Quartermaster, round 1. Writes the event calendars gathered
in edge/data/events/websearch-log.md into CSV, one row per date, with the
verification status of each row. Every date below is transcribed from that log;
none is generated by rule or recalled from memory. Also checks each date
against barqc's NYSE calendar (a statement on a non-session is flagged).

Status vocabulary
  URL          an official URL in the search result encodes the date
  PAGE         stated by the search tool's summary of the official page for that
               year (e.g. fomchistorical2005.htm, bls2005sched.pdf), no URL witness
  MINUTES-REF  only referenced inside another meeting's minutes ("next meeting ...")
  SECONDARY    from a non-official site summarised by the search tool
  UNVERIFIED   not retrieved (search budget exhausted) — no date given

Run: python3 -I -B events_build.py <tools/market dir> <out dir>
"""
import csv
import datetime as dt
import os
import sys

TOOLS, OUT = sys.argv[1:3]
sys.path.insert(0, TOOLS)
import barqc  # noqa: E402

RET = "2026-10-09T04:44Z..04:47Z (WebSearch; see websearch-log.md)"

# (statement/decision date, meeting as printed, status, query id)
FOMC = [
    # 2005 — Q2, fomchistorical2005.htm
    ("2005-02-02", "Feb 1-2", "URL", "Q2"), ("2005-03-22", "Mar 22", "URL", "Q2"), ("2005-05-03", "May 3", "URL", "Q2"),
    ("2005-06-30", "Jun 29-30", "URL", "Q2"), ("2005-08-09", "Aug 9", "URL", "Q2"), ("2005-09-20", "Sep 20", "PAGE", "Q2"),
    ("2005-11-01", "Nov 1", "PAGE", "Q2"), ("2005-12-13", "Dec 13", "URL", "Q2"),
    # 2006 — Q4
    ("2006-01-31", "Jan 31", "PAGE", "Q4"), ("2006-03-28", "Mar 27-28", "URL", "Q4"), ("2006-05-10", "May 10", "URL", "Q4"),
    ("2006-06-29", "Jun 28-29", "URL", "Q4"), ("2006-08-08", "Aug 8", "URL", "Q4"), ("2006-09-20", "Sep 20", "PAGE", "Q4"),
    ("2006-10-25", "Oct 24-25", "URL", "Q4"), ("2006-12-12", "Dec 12", "PAGE", "Q4"),
    # 2007 — Q5 + Q9
    ("2007-01-31", "Jan 30-31", "URL", "Q9"), ("2007-03-21", "Mar 20-21", "URL", "Q9"), ("2007-05-09", "May 9", "URL", "Q9"),
    ("2007-06-28", "Jun 27-28", "MINUTES-REF", "Q5"), ("2007-08-07", "Aug 7", "URL", "Q5"), ("2007-09-18", "Sep 18", "URL", "Q5"),
    ("2007-10-31", "Oct 30-31", "URL", "Q5"), ("2007-12-11", "Dec 11", "URL", "Q5"),
    # 2008 — Q6
    ("2008-01-30", "Jan 29-30", "URL", "Q6"), ("2008-03-18", "Mar 18", "URL", "Q6"), ("2008-04-30", "Apr 29-30", "URL", "Q6"),
    ("2008-06-25", "Jun 24-25", "URL", "Q6"), ("2008-08-05", "Aug 5", "URL", "Q6"), ("2008-09-16", "Sep 16", "URL", "Q6"),
    ("2008-10-29", "Oct 28-29", "URL", "Q6"), ("2008-12-16", "Dec 15-16", "URL", "Q6"),
    # 2009 — Q7
    ("2009-01-28", "Jan 27-28", "URL", "Q7"), ("2009-03-18", "Mar 17-18", "URL", "Q7"), ("2009-04-29", "Apr 28-29", "URL", "Q7"),
    ("2009-06-24", "Jun 23-24", "URL", "Q7"), ("2009-08-12", "Aug 11-12", "URL", "Q7"), ("2009-09-23", "Sep 22-23", "URL", "Q7"),
    ("2009-11-04", "Nov 3-4", "URL", "Q7"), ("2009-12-16", "Dec 15-16", "MINUTES-REF", "Q7"),
    # 2010 — Q8
    ("2010-01-27", "Jan 26-27", "PAGE", "Q8"), ("2010-03-16", "Mar 16", "PAGE", "Q8"), ("2010-04-28", "Apr 27-28", "PAGE", "Q8"),
    ("2010-06-23", "Jun 22-23", "PAGE", "Q8"), ("2010-08-10", "Aug 10", "PAGE", "Q8"), ("2010-09-21", "Sep 21", "URL", "Q8"),
    ("2010-11-03", "Nov 2-3", "URL", "Q8"), ("2010-12-14", "Dec 14", "URL", "Q8"),
    # 2011 — Q10
    ("2011-01-26", "Jan 25-26", "PAGE", "Q10"), ("2011-03-15", "Mar 15", "URL", "Q10"), ("2011-04-27", "Apr 26-27", "URL", "Q10"),
    ("2011-06-22", "Jun 21-22", "URL", "Q10"), ("2011-08-09", "Aug 9", "PAGE", "Q10"), ("2011-09-21", "Sep 20-21", "URL", "Q10"),
    ("2011-11-02", "Nov 1-2", "URL", "Q10"), ("2011-12-13", "Dec 13", "URL", "Q10"),
    # 2012 — Q11 + Q13
    ("2012-01-25", "Jan 24-25", "URL", "Q11"), ("2012-03-13", "Mar 13", "URL", "Q13"), ("2012-04-25", "Apr 24-25", "URL", "Q11"),
    ("2012-06-20", "Jun 19-20", "URL", "Q11"), ("2012-08-01", "Jul 31-Aug 1", "URL", "Q11"), ("2012-09-13", "Sep 12-13", "URL", "Q11"),
    ("2012-10-24", "Oct 23-24", "URL", "Q13"), ("2012-12-12", "Dec 11-12", "URL", "Q11"),
    # 2013 — Q12
    ("2013-01-30", "Jan 29-30", "PAGE", "Q12"), ("2013-03-20", "Mar 19-20", "URL", "Q12"), ("2013-05-01", "Apr 30-May 1", "PAGE", "Q12"),
    ("2013-06-19", "Jun 18-19", "URL", "Q12"), ("2013-07-31", "Jul 30-31", "PAGE", "Q12"), ("2013-09-18", "Sep 17-18", "URL", "Q12"),
    ("2013-10-30", "Oct 29-30", "PAGE", "Q12"), ("2013-12-18", "Dec 17-18", "URL", "Q12"),
    # 2014 — Q14 (April not returned)
    ("2014-01-29", "Jan 28-29", "URL", "Q14"), ("2014-03-19", "Mar 18-19", "URL", "Q14"), (None, "April 2014 meeting", "UNVERIFIED", "Q14"),
    ("2014-06-18", "Jun 17-18", "URL", "Q14"), ("2014-07-30", "Jul 29-30", "URL", "Q14"), ("2014-09-17", "Sep 16-17", "URL", "Q14"),
    ("2014-10-29", "Oct 28-29", "URL", "Q14"), ("2014-12-17", "Dec 16-17", "URL", "Q14"),
    # 2015 — Q15
    ("2015-01-28", "Jan 27-28", "PAGE", "Q15"), ("2015-03-18", "Mar 17-18", "URL", "Q15"), ("2015-04-29", "Apr 28-29", "PAGE", "Q15"),
    ("2015-06-17", "Jun 16-17", "URL", "Q15"), ("2015-07-29", "Jul 28-29", "URL", "Q15"), ("2015-09-17", "Sep 16-17", "URL", "Q15"),
    ("2015-10-28", "Oct 27-28", "URL", "Q15"), ("2015-12-16", "Dec 15-16", "URL", "Q15"),
    # 2016 — Q16
    ("2016-01-27", "Jan 26-27", "MINUTES-REF", "Q16"), ("2016-03-16", "Mar 15-16", "URL", "Q16"), ("2016-04-27", "Apr 26-27", "MINUTES-REF", "Q16"),
    ("2016-06-15", "Jun 14-15", "URL", "Q16"), ("2016-07-27", "Jul 26-27", "URL", "Q16"), ("2016-09-21", "Sep 20-21", "URL", "Q16"),
    ("2016-11-02", "Nov 1-2", "URL", "Q16"), ("2016-12-14", "Dec 13-14", "URL", "Q16"),
] + [(None, f"all {y} meetings", "UNVERIFIED", "-") for y in range(2017, 2025)] + [
    # 2025 — Q1, secondary (tentative schedule as summarised from texasbankers.com; tool: Fed page Jan/Mar/May match)
    ("2025-01-29", "Jan 28-29", "SECONDARY", "Q1"), ("2025-03-19", "Mar 18-19", "SECONDARY", "Q1"), ("2025-05-07", "May 6-7", "SECONDARY", "Q1"),
    ("2025-06-18", "Jun 17-18", "SECONDARY", "Q1"), ("2025-07-30", "Jul 29-30", "SECONDARY", "Q1"), ("2025-09-17", "Sep 16-17", "SECONDARY", "Q1"),
    ("2025-10-29", "Oct 28-29", "SECONDARY", "Q1"), ("2025-12-10", "Dec 9-10", "SECONDARY", "Q1"),
    # 2026 — Q1, fomccalendars.htm as summarised (no domain restriction; not URL-corroborated)
    ("2026-01-28", "Jan 27-28", "PAGE", "Q1"), ("2026-03-18", "Mar 17-18", "PAGE", "Q1"), ("2026-04-29", "Apr 28-29", "PAGE", "Q1"),
    ("2026-06-17", "Jun 16-17", "PAGE", "Q1"), ("2026-07-29", "Jul 28-29", "PAGE", "Q1"), ("2026-09-16", "Sep 15-16", "PAGE", "Q1"),
    ("2026-10-28", "Oct 27-28 (future at retrieval)", "PAGE", "Q1"), ("2026-12-09", "Dec 8-9 (future at retrieval)", "PAGE", "Q1"),
]

# Intermeeting actions FOUND (completeness not verified). statement_date only where the result states it.
FOMC_UNSCHED = [
    ("2007-08-10", "conference call (URL FOMC20070810confcall.pdf); a liquidity statement that day per the result", "URL", "Q5"),
    ("2007-08-16", "conference call; statement date not established by the search", "PAGE", "Q5"),
    ("2007-12-06", "conference call (Term Auction Facility proposals); statement date not established", "PAGE", "Q5"),
    ("2008-01-09", "conference call; no action stated", "PAGE", "Q6"),
    ("2008-01-22", "statement following the 2008-01-21 call ('statement text to be released the next morning')", "PAGE", "Q6"),
    ("2008-03-10", "conference call (liquidity / TSLF); statement date not established", "PAGE", "Q6"),
    ("2008-07-24", "joint session with the Board (liquidity facilities); statement date not established", "PAGE", "Q6"),
    ("2008-09-29", "conference call (swap lines); statement date not established", "PAGE", "Q6"),
    ("2008-10-08", "coordinated 50 bp cut decided on the 2008-10-07 call (URL FOMC20081007confcall.pdf)", "PAGE", "Q6"),
    ("2009-01-16", "conference call; no decision", "PAGE", "Q7"),
    ("2009-02-07", "joint call with the Board; statement date not established", "PAGE", "Q7"),
    ("2009-06-03", "joint call (URL FOMC20090603confcall.pdf); statement date not established", "URL", "Q7"),
    ("2010-05-09", "conference call WITH a statement (listed on fomchistorical2010.htm)", "PAGE", "Q8"),
    ("2010-10-15", "videoconference, no policy decision (URL FOMC20101015confcall.pdf)", "URL", "Q8"),
]

CPI = [  # (release date, reference month, status) — Q3
    ("2005-01-19", "2004-12", "PAGE"), ("2005-02-23", "2005-01", "PAGE"), ("2005-03-23", "2005-02", "PAGE"),
    ("2005-04-20", "2005-03", "PAGE"), ("2005-05-18", "2005-04", "URL"), ("2005-06-15", "2005-05", "PAGE"),
    (None, "2005-06", "UNVERIFIED"), ("2005-08-16", "2005-07", "URL"), ("2005-09-15", "2005-08", "URL"),
    ("2005-10-14", "2005-09", "PAGE"), ("2005-11-16", "2005-10", "URL"), ("2005-12-15", "2005-11", "PAGE"),
    ("2006-01-18", "2005-12", "PAGE"),
]

os.makedirs(OUT, exist_ok=True)
bad = []
with open(os.path.join(OUT, "fomc-statements-2005-2026.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["statement_date", "weekday", "nyse_session", "meeting_as_printed", "kind", "status", "query", "retrieved"])
    for d, m, s, q in FOMC:
        if d:
            day = dt.date.fromisoformat(d)
            sess = barqc.is_session_day(day)
            if not sess:
                bad.append(d)
            w.writerow([d, day.strftime("%a"), int(sess), m, "scheduled", s, q, RET])
        else:
            w.writerow(["", "", "", m, "scheduled", s, q, RET])
    for d, m, s, q in FOMC_UNSCHED:
        day = dt.date.fromisoformat(d)
        w.writerow([d, day.strftime("%a"), int(barqc.is_session_day(day)), m, "intermeeting (found; list not complete)", s, q, RET])

with open(os.path.join(OUT, "cpi-releases-2005.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["release_date", "weekday", "nyse_session", "reference_month", "status", "query", "retrieved"])
    for d, ref, s in CPI:
        if d:
            day = dt.date.fromisoformat(d)
            w.writerow([d, day.strftime("%a"), int(barqc.is_session_day(day)), ref, s, "Q3", RET])
        else:
            w.writerow(["", "", "", ref, s, "Q3", RET])

with open(os.path.join(OUT, "employment-situation-releases.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["release_date", "reference_month", "status", "note"])
    w.writerow(["", "2005-01..2026-09", "UNVERIFIED", "not retrieved: WebFetch has no DNS here and the WebSearch budget was exhausted"])

sched = [r for r in FOMC if r[0]]
from collections import Counter
st = Counter(r[2] for r in sched)
print(f"FOMC scheduled statement dates written: {len(sched)}; by status {dict(st)}; "
      f"unverified placeholders: {sum(1 for r in FOMC if not r[0])}; intermeeting found: {len(FOMC_UNSCHED)}")
print(f"FOMC dates that are NOT NYSE sessions by barqc's calendar: {bad or 'none'}")
print(f"CPI 2005: {sum(1 for r in CPI if r[0])} dated, {sum(1 for r in CPI if not r[0])} unverified")
